# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  workflow_call:

  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.4.13"
      - name: Set up Python 3.13
        run: uv python install 3.13
      - name: Install dependencies
        run: uv sync --all-extras
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.4.13"
      - name: Set up Python 3.13
        run: uv python install 3.13
      - name: Install dependencies
        run: uv sync --extra lint --extra dev
      - name: Lint with pre-commit
        run: uv run pre-commit run --all-files
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.4.13"
      - name: Set up Python 3.13
        run: uv python install 3.13
      - name: Install dependencies
        run: uv sync --extra test
      - name: Test with pytest
        run: uv run pytest
