# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  workflow_call:

  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.29"
      - name: Set up Python 3.13 venv
        run: uv venv -p 3.13 .venv
      - name: Activate venv
        run: source .venv/bin/activate
      - name: Install dependencies
        run: uv sync --all-groups --all-extras
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.29"
      - name: Set up Python 3.13 venv
        run: uv venv -p 3.13 .venv
      - name: Activate venv
        run: source .venv/bin/activate
      - name: Install dependencies
        run: uv sync --group dev
      - name: Lint with pre-commit
        run: uv run pre-commit run --all-files
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.29"
      - name: Set up Python 3.13 venv
        run: uv venv -p 3.13 .venv
      - name: Activate venv
        run: source .venv/bin/activate
      - name: Install dependencies
        run: uv sync --group test
      - name: Test with pytest
        run: uv run pytest
